export const SET_VISIBLE_TYPE = "SET_VISIBLE_TYPE";
export const SET_AUTHENTICATE = "SET_AUTHENTICATE";
export const SET_USER_ID = "SET_USER_ID";
export const SET_ACCOUNT_SETTING = "SET_ACCOUNT_SETTING";
export const SET_OPEN_SIGNUP = "SET_OPEN_SIGNUP";
